# Generated by Django 5.1.4 on 2025-01-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_date']},
        ),
        migrations.RemoveField(
            model_name='news',
            name='likes_count',
        ),
    ]
