# Generated by Django 5.1.4 on 2025-01-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_remove_news_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
