# Generated by Django 5.1.4 on 2025-01-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
