# Generated by Django 5.1.4 on 2025-01-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('superuser', 'Superuser'), ('registered', 'Registered User')], default='registered', max_length=20),
        ),
    ]
